# Generated by Django 2.1.4 on 2018-12-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181217_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Like'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
