# Generated by Django 2.1.4 on 2018-12-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181217_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.SmallIntegerField(default=2),
        ),
    ]
